name: PROD CI/CD to S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  PROD_MY_CICD_JOBS:
    runs-on: ubuntu-latest
    steps:
      - name: 레포 다운 받기
        uses: actions/checkout@v5

      - name: 의존성 설치 -> 빌드
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_LANDING_PAGE_URL: ${{ secrets.VITE_LANDING_PAGE_URL }}
          VITE_LOGIN_PAGE_URL: ${{ secrets.VITE_LOGIN_PAGE_URL }}
          VITE_SIGNUP_PAGE_URL: ${{ secrets.VITE_SIGNUP_PAGE_URL }}
          VITE_MYPAGE_PAGE_URL: ${{ secrets.VITE_MYPAGE_PAGE_URL }}
          VITE_STUDY_PAGE_URL: ${{ secrets.VITE_MYPAGE_PAGE_URL }}
          VITE_OUR_DOMAIN: ${{ secrets.VITE_STUDY_PAGE_URL }}
        run: |
          npm install
          npm run build

      - name: aws 권한 획득
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: s3 비우기
        run: aws s3 rm --recursive s3://oz-studyhub

      - name: s3에 dist 채우기
        run: aws s3 cp ./dist s3://oz-studyhub --recursive

      - name: cloudfront 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id E1U7I1LUZKZU25 --path "/*"
